### PR TITLE
Increase robustness of file transfers to remote

### PR DESCRIPTION
**Pull request by mgsb**
If the remote is slow initializing to receive a file, the first
buffer sent from host to remote may overflow the UART buffer.
To fix this, the "ack" mechanism was moved to the beginning of
the loop so the first buffer write waits for the remote.

In debugging this, it was observed that the dev.read() of the ack
would not timeout causing an indefinite "hang". A timeout was
added to send_file_to_remote() to catch issues on the remote.
The timeout methods were changed to getter/setter properties to
enable (re)setting the timeout to None which indicates block
forever on a serial read.

### CODE REVIEW

**Comment by dhylands** [comment]
Very nice! Today is a travel day for me, so hopefully I'll get a chance to try this out in the next couple days.

**Comment by mgsb** [comment]
Any feedback on this?

**Comment by dhylands** [comment]
Sorry to take to long. Thanks for the fix - merged in https://github.com/dhylands/rshell/commit/75695463438044c38ebdb32347ead80e4194e592

**Comment by dhylands** [comment]
And created version 0.0.13 which includes this PR

**Comment by mgsb** [comment]
No problem - thanks much for the useful utility and accepting tweaks!

**Pull request merged**
